### ISSUE TITLE
Other video formats than ONI

### ISSUE THREAD

**Issue by FranciscoSola** [danielelic/deep-segmentation#4]
Hi Daniele, thanks again for your code, it's been very useful.

I'm wondering how I can articulate this code with video files in more traditional formats such as .mov, .avi or .mp4. Is it possible to convert these videos to .oni? What's the origin of an .oni video? Or do you have any other idea that could help me?

Thanks!

**Comment by danielelic** [comment]
Hi Francisco, I used `.oni`files because the dataset consists of RGBD images. You can adapt the script with any video input format.
